name: iOS Build and Test with SonarCloud

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: '14.2'

    - name: Install Slather
      run: gem install slather

    - name: Build and Run Tests
      run: |
        xcodebuild clean build test \
          -project TwitterClone.xcodeproj \
          -scheme TwitterClone -derivedDataPath Build/ \
          -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro' \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        slather coverage --sonarqube-xml --scheme TwitterClone TwitterClone.xcodeproj
        
    - name: SonarCloud Analysis
      run: |
        curl -o sonar-scanner.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.0.2966-macosx.zip
        unzip -o sonar-scanner.zip
        export PATH=$PATH:$(pwd)/sonar-scanner-4.6.2.2472-macosx/bin
        

        sonar-scanner \
          -Dsonar.projectKey=amrhossam96_TwitterClone \
          -Dsonar.organization=amrhossam96 \
          -Dsonar.sources=. \
          -Dsonar.tests=TwitterCloneTests \
          -Dsonar.test.inclusions=**/*.swift \
          -Dsonar.coverageReportPaths=coverage/cobertura.xml \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.swift.coverage.reportPaths=coverage/cobertura.xml \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.c.file.suffixes=- \
          -Dsonar.cpp.file.suffixes=- \
          -Dsonar.objc.file.suffixes=-
